application: osmdonetsk
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /admin.*
  script: admin.py
  login: admin

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
  mime_type: image/x-icon

- url: /.*
  script: main.py
