title: Правки OpenStreetMap в Донецке
twitter_username: OSMDonetsk
twitter_url: twitter.com/OSMDonetsk
bitly_username: your_bitly_username if login with twitter see http://bitly.com/a/your_api_key
bitly_key: your_key
consumer_key: your_app_twitter_consumer_key
consumer_secret: your_app_twitter_consumer_secret
bbox: 37.4084473,47.8371271,38.2131958,48.1990490
